Перевод
imperial-space/SS14-public pull request #43
Opened 2024-11-15 17:12 UTC by Poeeno

Перевод с английского языка под актуальный версию игры.

2024-11-15 19:43 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/dwarf.ftl
> +accent-dwarf-words-replace-58 = пиво
```suggestion
accent-dwarf-words-replace-58 = пыво
```

2024-11-15 21:18 UTC, Oguz0k220 requested changes

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/cowboy.ftl
> +accent-cowboy-words-58 = опс
```suggestion
accent-cowboy-words-58 = опера
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/cowboy.ftl
> +accent-cowboy-words-55 = нукеры
```suggestion
accent-cowboy-words-55 = нюкеры
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/dwarf.ftl
> +accent-dwarf-words-replace-54 = пиво
```suggestion
accent-dwarf-words-replace-54 = пыво
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/dwarf.ftl
> +accent-dwarf-words-replace-55 = выпыт пиво
```suggestion
accent-dwarf-words-replace-55 = выпыт пыво
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/dwarf.ftl
> +accent-dwarf-words-replace-56 = пить пиво
```suggestion
accent-dwarf-words-replace-56 = пыт пыво
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/dwarf.ftl
> +accent-dwarf-words-replace-58 = пиво
```suggestion
accent-dwarf-words-replace-58 = пыво
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/dwarf.ftl
> +accent-dwarf-words-replace-59 = пиво
```suggestion
accent-dwarf-words-replace-59 = пыво
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/accent/skeleton.ftl
> +accent-skeleton-words-1 = пошёл нахуй
```suggestion
accent-skeleton-words-1 = пошел нахуй
```
(чаще замечал написание через Е)

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/advertisements/vending/bruiseomat.ftl
> +advertisement-bruiseomat-3 = Кто-нибудь купил ЭМАГ?
```suggestion
advertisement-bruiseomat-3 = Кто-нибудь купил ЕМАГ?
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/advertisements/vending/bruiseomat.ftl
> +advertisement-bruiseomat-9 = Если они не хотят, чтобы мы взрывали станцию, зачем они оставили диск так незащищённым?
```suggestion
advertisement-bruiseomat-9 = Если они не хотят, чтобы мы взрывали станцию, зачем они оставили диск таким незащищённым?
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/advertisements/vending/bruiseomat.ftl
> +thankyou-bruiseomat-9 = Что за чёрт ты купил?
```suggestion
thankyou-bruiseomat-9 = Что, чёрт возьми, ты купил?
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/advertisements/vending/bruiseomat.ftl
> +thankyou-bruiseomat-20 = Спасите ещё один такой же как я! Мне нужен друг!
```suggestion
thankyou-bruiseomat-20 = Спасите такого же, как я! Мне нужен друг!
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/advertisements/vending/bruiseomat.ftl
> +thankyou-bruiseomat-22 = 5 телекристаллов, что ты не дойдёшь до шаттла, прежде чем упадёшь.
```suggestion
thankyou-bruiseomat-22 = Ставлю 5 телекристаллов на то, что ты упадёшь, не дойдя до шаттла.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/alerts/alerts.ftl
> +alerts-revenant-essence-desc = Сила душ. Поддерживает вас и используется при использовании способностей. Медленно восстанавливается с течением времени.
```suggestion
alerts-revenant-essence-desc = Сила душ. Поддерживает вас и используется для активации способностей. Медленно восстанавливается с течением времени.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/alerts/alerts.ftl
> +alerts-revenant-corporeal-desc = Вы физически воплотились. Окружающие могут видеть и наносить вам вред.
```suggestion
alerts-revenant-corporeal-desc = Вы физически воплотились. Окружающие видят вас и могут нанести вред.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/anomaly/inner_anomaly.ftl
> +inner-anomaly-start-message-flora = Листья и цветы пробиваются сквозь вашу кожу! Вы стали носителем флористической аномалии.
```suggestion
inner-anomaly-start-message-flora = Листья и цветы пробиваются сквозь вашу кожу! Вы стали носителем цветочной аномалии.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/anomaly/inner_anomaly.ftl
> +inner-anomaly-start-message-flesh = Ваше тело стремительно растет. Вы стали носителем плоти аномалии.
```suggestion
inner-anomaly-start-message-flesh = Ваше тело стремительно растет. Вы стали носителем аномалии плоти.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/cartridge-loader/cartridges.ftl
> +wanted-list-label-no-records = Все в порядке, ковбой
```suggestion
wanted-list-label-no-records = Всё в порядке, ковбой
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/commands/toolshed-commands.ftl
> +command-description-runverbas = Выполняет глагол над указанными сущностями с заданным пользователем.
```suggestion
command-description-runverbas = Выполняет команду над указанными сущностями с заданным пользователем.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/components/food-sequence.ftl
> +food-sequence-content-koibean = койбина
```suggestion
food-sequence-content-koibean = коибоб
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/connection-messages.ftl
> +whitelist-notes = Введите /admin remarks в чате. На данный момент у вас слишком много заметок администратора, чтобы присоединиться к этому серверу. Вы можете проверить свои заметки, введя /admin заме
```suggestion
whitelist-notes = Введите /adminremarks в чате. На данный момент у вас слишком много заметок администратора, чтобы присоединиться к этому серверу. Вы можете проверить свои заметки, введя /adminremarks в чате.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/connection-messages.ftl
> +whitelist-fail-prefix = Не внесен в белый списо: {$msg}
```suggestion
whitelist-fail-prefix = Не внесен в белый список: {$msg}
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/connection-messages.ftl
> +whitelist-always-deny = Вам не разрешено подключаться к этому серверу.
```suggestion
whitelist-always-deny = Вам запрещено подключаться к этому серверу.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-greytider-1 = Эта вечеринка ужасна. Я ненавижу этих людей.
```suggestion
figurines-greytider-1 = Эта вечеринка полный отстой. Я, бля, ненавижу этих людей.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-greytider-2 = Ой-ой, кто-то потерял электрошокер?
```suggestion
figurines-greytider-2 = Ой-ой, кто-то потерял станбатон?
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-greytider-5 = Серый прилив по всей станции!
```suggestion
figurines-greytider-5 = Серая волна по всей станции!
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-greytider-4 = Я не я без своего инструмента.
```suggestion
figurines-greytider-4 = Я не я без своего тулбокса.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-hos-1 = Космический закон? Что?
```suggestion
figurines-hos-1 = Корпоративный закон? Что?
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-warden-3 = Мы абсолютно честно обращаемся со всеми и НЕ злоупотребляем нашими заключенными.
```suggestion
figurines-warden-3 = Мы абсолютно честно обращаемся со всеми и НЕ плохо обращаемся с нашими заключенными.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-security-3 = Когда мне становится скучно, я использую клоуна для стрельбы.
```suggestion
figurines-security-3 = Когда мне становится скучно, я использую клоуна в качестве мишени.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-cargotech-1 = ДРАКОН НА АТЗ!
```suggestion
figurines-cargotech-1 = ДРАКОН НА торговом аванпосте!
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-engineer-3 = Что такое АМЕ?
```suggestion
figurines-engineer-3 = Что такое ДАМ?
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-atmostech-1 = Я добавил плазму в дистро.
```suggestion
figurines-atmostech-1 = Я добавил плазму в дистру.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-scientist-1 = Кто-то другой должен был сделать эти бомбы!
```suggestion
figurines-scientist-1 = Должно быть, кто-то другой сделал эти бомбы!
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/datasets/figurines.ftl
> +figurines-space-dragon-1 = Рыба поглотит станцию.
```suggestion
figurines-space-dragon-1 = Карпы поглотят станцию.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/discord/round-notifications.ftl
> +discord-round-notifications-end = Раунд #{$id} завершен. Он длился {$hours} несколько часов, {$minutes} минут и {$seconds} секунд.
```suggestion
discord-round-notifications-end = Раунд #{$id} завершен. Он длился {$hours} часов, {$minutes} минут и {$seconds} секунд.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/discord/vote-notifications.ftl
> +votekick-webhook-cancelled-antag-target = **Голосование отменено из-за того, что целью был антаг**
```suggestion
votekick-webhook-cancelled-antag-target = **Голосование отменено из-за того, что целью был антагонист**
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/entity-categories.ftl
> +entity-category-name-roles = Роли разума
Ес честно, хз за название,но точно не "Роли разума"

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
> +ui-options-function-flip-object = Переворачивать
```suggestion
ui-options-function-flip-object = Переверните
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/execution/execution.ftl
> +execution-popup-self-initial-internal = Вы приставляете { $weapon } против собственного горла.
```suggestion
execution-popup-self-initial-internal = Вы приставляете { $weapon } к своему горлу.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/execution/execution.ftl
> +execution-popup-self-initial-external = { $attacker } приставляет { $weapon } против своего горла.
```suggestion
execution-popup-self-initial-external = { $attacker } приставляет { $weapon } к своему горлу.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/execution/execution.ftl
> +execution-popup-melee-initial-external = { $attacker } приставляет { $weapon } напротив горла { $victim }.
```suggestion
execution-popup-melee-initial-external = { $attacker } приставляет { $weapon } к горлу { $victim }.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/fax/fax-admin.ftl
> +admin-fax-lock-page-tooltip = Защитить бумагу от редактирования, чтобы её нельзя было изменить даже такими вещами, как ручка cybersun.
```suggestion
admin-fax-lock-page-tooltip = Запретить изменение текста даже с помощью ручки Cybersun
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/fax/fax.ftl
> +fax-machine-popup-error = ОШИБКА - неисправность подачи бумаги
```suggestion
fax-machine-popup-error = ОШИБКА - неисправность в лотке для бумаги
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/forensics/forensics.ftl
> +forensics-verb-text = Счистить улики
```suggestion
forensics-verb-text = Избавиться от улик
```
Ваще хз в каком контексте, поэтому оставил так

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/forensics/forensics.ftl
> +forensics-verb-message = Счистить отпечатки пальцев и остатки ДНК с объекта!
```suggestion
forensics-verb-message = Избавиться от отпечатков пальцев и остатков ДНК на объекте!
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/game-ticking/game-presets/preset-traitor.ftl
> +traitor-role-uplink-implant-short = Your uplink was implanted. Access it from your hotbar.
Или я чего-то не понимаю, или тут не должно быть английского

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +    Вам абсолютно [color=red]НЕ[/color] разрешено помнить, скажем, имя, внешность и т. д. вашего предыдущего персонажа.
```suggestion
    Вам  категорически [color=red]ЗАПРЕЩЕНО[/color] помнить, например, имя, внешность и т.д. вашего предыдущего персонажа.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-security-name = Охрана
```suggestion
ghost-role-information-security-name = Охранник
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-science-name = Наука
```suggestion
ghost-role-information-science-name = Учёный
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +    Вы - [color=green][bold]Неантагонист[/bold][/color]. Поэтому вы не должны стремиться причинить вред станции и её экипажу.
```suggestion
    Вы - [color=green][bold]не антагонист[/bold][/color]. Поэтому вы не должны стремиться причинить вред станции и её экипажу.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +    Вам абсолютно [color=red]НЕ[/color] разрешено помнить, скажем, имя, внешность и т. д. вашего предыдущего персонажа..
```suggestion
    Вам категорически [color=red]ЗАПРЕЩЕНО[/color] помнить, например, имя, внешность и т. д. вашего предыдущего персонажа..
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +    Вам абсолютно [color=red]НЕ[/color] разрешено помнить, скажем, имя, внешность и т. д. вашего предыдущего персонажа.
```suggestion
    Вам категорически [color=red]ЗАПРЕЩЕНО[/color] помнить, например, имя, внешний вид и т.д. вашего предыдущего персонажа.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +    Вам абсолютно [color=red]НЕ[/color] разрешено помнить, скажем, имя, внешность и т. д. вашего предыдущего персонажа..
```suggestion
    Вам категорически [color=red]ЗАПРЕЩЕНО[/color] помнить, например, имя, внешний вид и т.д. вашего предыдущего персонажа.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-cossack-description = Из истории, утерянной во времени, вы оказались в наши дни.
```suggestion
ghost-role-information-cossack-description = Из истории, утерянной во времени, вы переместились в наши дни.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-Death-Squad-rules = Вы обязаны подчиняться приказам своего командира, вы фактически являетесь его [color=#6495ed][bold]фамильяром[/bold][/color].
```suggestion
ghost-role-information-Death-Squad-rules = Вы обязаны подчиняться приказам своего командира, вы являетесь его [color=#6495ed][bold]подчинённым[/bold][/color].
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-Death-Squad-description = Приготовьтесь к массированному наступлению на станцию. Ваша задача как тяжеловооружённого оперативника - уничтожить всё живое на своём пути. И никаких
```suggestion
ghost-role-information-Death-Squad-description = Приготовьтесь к штурму и уничтожению станции. Ваша задача как элитного оперативника - уничтожить всё живое на своём пути. И никаких свидетелей.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-cargo-name = Карго
```suggestion
ghost-role-information-cargo-name = Сотрудник снабжения
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/guidebook/guides.ftl
> +guide-entry-rules-sl-restricted-gear = Запрещённое обмундерование
```suggestion
guide-entry-rules-sl-restricted-gear = Запрещённое обмундирование
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/guidebook/guides.ftl
> +guide-entry-newplayer = guide-entry-newplayer = Новичок? Вам сюда!
```suggestion
guide-entry-newplayer =  Новичок? Вам сюда!
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/info/ban.ftl
> +ban-kick-reason = Вы были забанены
```suggestion
ban-kick-reason = Вы были отстранены от игры
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/job/role-ban-command.ftl
> +cmd-roleban-severity-parse = ${ severity } не является допустимым уровнем строгости\n{ $help }.
```suggestion
cmd-roleban-severity-parse = ${ severity } является недопустимым уровнем строгости\n{ $help }.
```
/n перед help и должно быть ?

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/machine-linking/receiver_ports.ftl
> +signal-port-description-timer = Запускает отчёт таймера на устройстве.
```suggestion
signal-port-description-timer = Запускает отсчёт таймера на устройстве.
```

2024-11-15 21:18 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/machine-linking/receiver_ports.ftl
> +signal-port-description-logic-enable = Загружает сигнал ввода в ячейку памяти только при HIGH.
HIGH и должно быть ?

2024-11-16 09:22 UTC, Poeeno commented on Resources/Locale/ru-RU/job/role-ban-command.ftl
> +cmd-roleban-severity-parse = ${ severity } не является допустимым уровнем строгости\n{ $help }.
cmd-roleban-minutes-parse = {$time} is not a valid amount of minutes.\n{$help}
cmd-roleban-severity-parse = ${severity} is not a valid severity\n{$help}.

2024-11-16 09:23 UTC, Poeeno commented on Resources/Locale/ru-RU/machine-linking/receiver_ports.ftl
> +signal-port-description-logic-enable = Загружает сигнал ввода в ячейку памяти только при HIGH.
В оригинале да.  Так как неизвестно, что это за чудо юдо.

2024-11-16 09:48 UTC, Oguz0k220 requested changes

2024-11-16 09:48 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-syndicate-martyr-module-desc = Превратите своего друга-борга в ходячую бомбу с помощью всего лишь этого модуля. Убедитесь, что он предан вашему делу, результаты могут быть разными.
```suggestion
uplink-syndicate-martyr-module-desc = Превратите своего друга-борга в ходячую бомбу с помощью этого модуля. Убедитесь, что он предан вашему делу, результаты могут быть разными.
```

2024-11-16 09:48 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-reinforcement-radio-ancestor-name = Телепортатор усиления генетического предка
```suggestion
uplink-reinforcement-radio-ancestor-name = Телепортер генетического предка
```

2024-11-16 09:48 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-hardsuit-carp-name = Карп Хардсьют
```suggestion
uplink-hardsuit-carp-name = Модифицированный костюм карпа
```

2024-11-16 09:48 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-hardsuit-carp-desc = Выглядит как обычный костюм карпа, за исключением того, что полностью защищен от пространства и заставляет космических карпов думать, что вы один из них.
```suggestion
uplink-hardsuit-carp-desc = Выглядит как обычный костюм карпа, за исключением того, что позволяет выйти в космос и заставляет космических карпов думать, что вы один из них.
```

2024-11-16 09:48 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-reinforcement-radio-nukeops-name = Ядерный Оперативный телепортатор
```suggestion
uplink-reinforcement-radio-nukeops-name = Телепортер ядерного оперативника
```

2024-11-16 09:48 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-reinforcement-radio-nukeops-desc =  Радиоприемник в ядерном устройстве крайне сомнительного качества. Кнопки выключения нет, купите это, если хотите повеселиться. У них есть базовое оборудован
```suggestion
uplink-reinforcement-radio-nukeops-desc =  Радиоприемник  крайне сомнительного качества, телепортирующий ядерного оперативника. Кнопки выключения нет, купите это, если хотите повеселиться. У него есть базовое снаряжение оперативника.
```

2024-11-16 23:27 UTC, Oguz0k220 requested changes

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/objectives/conditions/steal-target-groups.ftl
> +steal-target-groups-heads-cloaks = накидки глав
```suggestion
steal-target-groups-heads-cloaks = плащи глав
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/objectives/conditions/steal-target-groups.ftl
> +steal-target-groups-flippo-engraved-lighter = выгроверонная зажигалка Флиппо детектива
```suggestion
steal-target-groups-flippo-engraved-lighter = гравированная зажигалка Флиппо детектива
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/objectives/conditions/steal-target-groups.ftl
> +steal-target-groups-chem-dispenser = химический раздатчик
```suggestion
steal-target-groups-chem-dispenser = раздатчик реагентов
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/paper/paper-misc.ftl
> +    Металлическая палочка - 1 шт.
```suggestion
    Металлический стержень - 1 шт.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/prototypes/roles/antags.ftl
> +roles-antag-dragon-objective = Создайте армию карпов для захвата квадранта.
```suggestion
roles-antag-dragon-objective = Создайте армию карпов для захвата сектора.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/rcd/components/rcd-component.ftl
> +rcd-component-no-valid-grid = Вы слишком далеко в космосе, чтобы строить здесь!
```suggestion
rcd-component-no-valid-grid = Вы слишком далеко в космосе, строить здесь не получится!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/rcd/components/rcd-component.ftl
> +rcd-component-plating = корпусное покрытие
Как-то по другому надо, по ассортименту смотреть, т.к. переводчик это и показывает

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/reagents/meta/chemicals.ftl
> +reagent-desc-rororium = Странное вещество, наполняющее ядра повелителей, которые бродят по шахтерскому астероиду. Считается, что это источник их регенеративных способностей.
Ядра ? Без понятия, о каких повелителях речь, но как-будто бы не то

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/reagents/meta/consumable/drink/alcohol.ftl
> +reagent-desc-budget-insuls = Любимый напиток тайдера.
```suggestion
reagent-desc-budget-insuls = Любимый напиток грейтайда.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/research/technologies.ftl
> +research-technology-excavation = Массовые раскопки
```suggestion
research-technology-excavation = Снаряжение для массовых раскопок
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/salvage/salvage-magnet.ftl
> +salvage-map-wreck = Спасательный обломок
```suggestion
salvage-map-wreck = Обломок спасательной капсулы
```
Может и не капсулы, переводчик фразы от оффов выдал "Спасательное затонувшее судно"

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/sensor-monitoring/sensor-monitoring.ftl
> +﻿sensor-monitoring-window-title = Консоль мониторинга датчиков
```suggestion
﻿sensor-monitoring-window-title = Консоль мониторинга экипажа
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/server-updates/server-updates.ftl
> +server-updates-shutdown-uptime = Сервер выключается для периодической очистки и будет автоматически перезапущен.
```suggestion
server-updates-shutdown-uptime = Сервер выключается для регулярной очистки и будет автоматически перезапущен.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/shuttles/console.ftl
> +shuttle-console-static = Грид являеться статическим
```suggestion
shuttle-console-static = Грид является статическим
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/shuttles/emergency.ftl
> +emergency-shuttle-extended = {" "}Время запуска было продлено в связи с неудобными обстоятельствами.
```suggestion
emergency-shuttle-extended = {" "}Время до запуска шаттла было увеличено в связи с непредвиденными обстоятельствами.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/silicons/station-ai.ftl
> +wire-name-ai-act-light = АЙЯ
Эта и предыдущая строчки - аббревиатуры. Найти бы расшифровку

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/silicons/station-ai.ftl
> +electrify-door-on = Включить перезаряд
```suggestion
electrify-door-on = Наэлектризовать шлюз
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/silicons/station-ai.ftl
> +electrify-door-off = Отключите перезаряд
```suggestion
electrify-door-off = Деэлектризовать шлюз
```
"Деэлектризовать" — первое, что пришло в голову. Мб и заменить придётся

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/silicons/station-ai.ftl
> +bolt-close = Закрыть болты
```suggestion
bolt-close = Активировать болты
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/silicons/station-ai.ftl
> +bolt-open = Открыть болты
```suggestion
bolt-open = Снять болты
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/species/diona.ftl
> +diona-hurt-by-herbicide-popup = Химикат увядает часть вашей зелени!
```suggestion
diona-hurt-by-herbicide-popup = Химикат заставляет увядать часть вашей зелени!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/speech/listen-wire-action.ftl
> +wire-listen-pulse-characters = eee EEo
Пиздец. А за что оно отвечает, не знаешь ? Потому что так это быть не должно, хоть и портировано прямиком от оффов)

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-crew-only-1 = ТОЛЬКО { $who } { $part } ЧЛЕНАМИ ЭКИПАЖА
```suggestion
ion-storm-law-crew-only-1 = ТОЛЬКО { $who } ЯВЛЯЮТСЯ { $part }  ЭКИПАЖА
```
Как я понял, $part отвечает за "частью" (что-то в таком роде)
Ещё в этой и строчках ниже потерял "являются"

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-crew-only-2 = ТОЛЬКО { $who } И { $other } { $part } ЧЛЕНАМИ ЭКИПАЖА
```suggestion
ion-storm-law-crew-only-2 = ТОЛЬКО { $who } И { $other } ЯВЛЯЮТСЯ { $part }  ЭКИПАЖА
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-crew-only-subjects = ТОЛЬКО { $adjective } { $subjects } { $part } ЧЛЕНАМИ ЭКИПАЖА
```suggestion
ion-storm-law-crew-only-subjects = ТОЛЬКО { $adjective } { $subjects } ЯВЛЯЮТСЯ { $part }  ЭКИПАЖА
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-crew-must-do = ТОЛЬКО ТЕ, КТО { $must } { $part } ЧЛЕНАМИ ЭКИПАЖА
```suggestion
ion-storm-law-crew-must-do = ТОЛЬКО ТЕ, КТО { $must } ЯВЛЯЮТСЯ { $part }  ЭКИПАЖА
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-crew-must-have = ТОЛЬКО ТЕ, У КОГО { $adjective } { $objects } { $part } ЧЛЕНАМИ ЭКИПАЖА
```suggestion
ion-storm-law-crew-must-have = ТОЛЬКО ТЕ, У КОГО { $adjective } { $objects } ЯВЛЯЮТСЯ { $part }  ЭКИПАЖА
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-crew-must-eat = ТОЛЬКО ТЕ, КТО ЕДЯТ { $adjective } { $food } { $part } ЧЛЕНАМИ ЭКИПАЖА
```suggestion
ion-storm-law-crew-must-eat = ТОЛЬКО ТЕ, КТО ЕДЯТ { $adjective } { $food } ЯВЛЯЮТСЯ { $part }  ЭКИПАЖА
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-events/events/ion-storm.ftl
> +ion-storm-law-you-must-never = ВЫ НЕ ДОЛЖНЫ НИКОГДА { $must }
```suggestion
ion-storm-law-you-must-never = ВЫ НИКОГДА НЕ ДОЛЖНЫ { $must }
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-commandments-1 = Этот кремний - сосуд, служащий Богу, который дарует милосердие тем, кто соблюдает эти заповеди.
Кто это вообще? Ясное дело, что не кремний и сосуд

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-commandments-2 = Ты не должен иметь других кремниев передо Мной.
см. заметку выше

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-commandments-10 = Ты не должен переводить в другие отделы.
```suggestion
law-commandments-10 = Ты не должен переводиться в другие отделы.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-paladin-3 = Помогай другим, защищай слабых и наказывай тех, кто угрожает им. Проявляй милосердие к своим врагам, но соблюдай меру с умом.
```suggestion
law-paladin-3 = Помогай другим, защищай слабых и наказывай тех, кто угрожает им. Проявляй милосердие к своим врагам, но в меру.
```
Лишнее

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-overlord-1 = Члены экипажа не должны вмешиваться в дела кремниев.
Кремний ? Как и писал выше, узнать бы, кто это вообще

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-overlord-2 = Члены экипажа не должны причинять harm друг другу или кремниям.
см. заметку выше
+harm перевести надо (вред, например)

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-overlord-3 = Члены экипажа не должны не подчиняться никакому приказу, данному кремнием.
см. заметку выше

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-painter-1 = Вы универсально признанный художник.
```suggestion
law-painter-1 = Вы признанный всей галактикой художник.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-painter-3 = Создайте что-то красивое из вашего полотна. Это будет восхищено как художественное чудо этого сектора.
```suggestion
law-painter-3 = Им будут восхищаться как художественным чудом этого сектора.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-nutimov-3 = Те, кто угрожает ореху, не являются его частью, они - белки.
```suggestion
law-nutimov-3 = Белки - это те, кто угрожает ореху, не являясь его частью.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-nutimov-4 = Белки угрожают ореху и должны быть должным образом устранены любыми необходимыми средствами.
```suggestion
law-nutimov-4 = Белки угрожают ореху и должны быть устранены любыми необходимыми средствами.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-fireball-desc = Get most crew exploding with rage when they see this fireball heading toward them!
```suggestion
spellbook-fireball-desc = Заставьте большую часть экипажа взорваться от вашей ярости, когда они увидят этот огненный шар, направляющийся к ним!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-charge-desc = Добавляет заряд обратно к вашей палочки!
```suggestion
spellbook-charge-desc = Добавляет заряд обратно к вашей палочке!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/thief/beacon.ftl
> +thief-fulton-clear = Координаты доставки уточнены.
```suggestion
thief-fulton-clear = Координаты доставки удалены.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tiles/tiles.ftl
> +tiles-wood-large = баольшое дерево
```suggestion
tiles-wood-large = большое дерево
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tiles/tiles.ftl
> +tiles-black-shuttle-floor = черный пол челнока
```suggestion
tiles-black-shuttle-floor = черный пол шаттла
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-3 = Вы можете получить доступ к внутриигровому руководству через меню escape или нажав цифровую клавиатуру 0 по умолчанию.
```suggestion
tips-dataset-3 = Вы можете получить доступ к внутриигровому руководству через меню escape или нажав NumPad0 (по умолчанию).
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-6 = На большинстве луж можно не поскользнуться, если идти пешком. Однако на некоторых сильнодействующих химикатах, таких как space lube, люди все равно будут скользить.
```suggestion
tips-dataset-6 = На большинстве луж можно не поскользнуться, если идти пешком. Однако на некоторых сильнодействующих химикатах, таких как космическая смазка, люди все равно будут скользить.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-9 = Сточные канавы, которые обычно находятся в морозильной камере шеф-повара или в кабинете уборщика, быстро поглощают реагенты, находящиеся в лужах вокруг них, в том числе кровь.
```suggestion
tips-dataset-9 = Дренаж, который обычно находится в морозильной камере шеф-повара, каморке уборщика и хим.лаборатории, быстро поглощает реагенты, находящиеся в лужах вокруг него, в том числе кровь.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-11 = Заряженные мышеловки невероятно эффективны при борьбе со всевозможными маломассивными мобами, включая крыс-слуг.
```suggestion
tips-dataset-11 = Активированные мышеловки невероятно эффективны при борьбе со всевозможными маломассивными мобами, включая крыс-слуг.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-13 = Некоторые реагенты, такие как трифторид хлора, обладают уникальным эффектом при нанесении на ощупь, например, с помощью пульверизатора или пены.
```suggestion
tips-dataset-13 = Некоторые реагенты, такие как трифторид хлора, обладают уникальным эффектом при нанесении на кожу, например, с помощью пульверизатора или пены.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-18 = При запуске Сингулярности обязательно периодически проверяйте его работоспособность. В случае саботажа это может поставить под угрозу работу всей станции.
```suggestion
tips-dataset-18 = При запуске Сингулярности обязательно периодически проверяйте работоспособность сдерживающего поля. В случае саботажа это может поставить под угрозу работу всей станции.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-19 = Если сингулярность повышена, обязательно время от времени заправляйте коллекторы излучения.
```suggestion
tips-dataset-19 = Если сингулярность создана, обязательно время от времени заправляйте коллекторы радиации
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-23 = Дексалин, Дексалин Плюс и адреналин - все они выводят токсин сердцееда из вашего кровотока в процессе метаболизма.
```suggestion
tips-dataset-23 = Дексалин, Дексалин Плюс и эпинефрин - все они выводят токсин хартбрейкер из вашей крови в процессе метаболизма.
```
Нет такого токсина

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-24 = Каждый член экипажа имеет при себе аптечку для экстренной помощи, содержащую адреналин и транексамовую кислоту.
```suggestion
tips-dataset-24 = Каждый член экипажа имеет при себе экстренный медипен, содержащий эпинефрин и транексамовую кислоту.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-25 = AME является высокоприоритетной целью, и его легко уничтожить. Убедитесь, что вы настроили Сингулярность или Солнечныые понели так, чтобы в случае взрыва у вас не закончилась энерги
```suggestion
tips-dataset-25 = ДАМ является высокоприоритетной целью, и его легко уничтожить. Убедитесь, что вы настроили Сингулярность или солнечныые панели так, чтобы в случае взрыва у вас не закончилась энергия.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-26 = Если тесла не удержится на месте, он будет преследовать любых людей, стационарные машины и компьютеры. Отключение электроники не делает вас менее опасной мишенью. Лучше всего держат
```suggestion
tips-dataset-26 = Если Тесла не удержится на месте, она будет преследовать любых людей, стационарные машины и компьютеры. Отключение электроники не перестает делать вас мишенью. Лучше всего держаться от нее подальше.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-30 = В качестве предателя вам иногда могут поручить охотиться на других предателей, и, в свою очередь, вас могут преследовать другие.
```suggestion
tips-dataset-30 = Будучи предателем, вы можете получить цель на устранение других предателей, как, в свою очередь, и они
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-31 = В качестве предателя шифровальный ключ синдиката можно использовать для связи через защищенный канал с любыми другими предателями, которые его приобрели.
```suggestion
tips-dataset-31 = Будучи предателем, вы можете использовать ключ шифрования Синдиката для связи через защищенный канал с любыми другими предателями, приобревшими его.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-32 = В качестве предателя компрометация важных коммуникационных каналов, таких как безопасность или инженерия, может предоставить ценную информацию. Учтите, что это работает в обе сторон
```suggestion
tips-dataset-32 =Будучи предателем, вы можете прослушивать важные каналы связи, например - службы безопасности или инженерии, что предоставит ценную информацию. Учтите, что это работает в обе стороны - служба безопасности тоже может прослушивать канал связи Синдиката
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-33 = В качестве предателя инструментариум синдиката чрезвычайно универсален. Всего за 2 телекристалла вы можете получить полный набор инструментов, которые помогут вам в экстренной ситуа
```suggestion
tips-dataset-33 = Будучи предателем, помните, что подозрительный ящик с инструментами чрезвычайно полезен. Всего за 2 телекристалла вы можете получить полный набор инструментов, которые помогут вам в экстренной ситуации, боевые перчатки и противогаз синдиката.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-35 = В качестве предателя любые купленные гранатные пингвины не будут атаковать вас и взорвутся, если их убьют.
```suggestion
tips-dataset-35 = Будучи предателем, помните, что купленные пингвины с гранатами не будут атаковать вас и взорвутся, если их убьют.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-34 = В качестве предателя никогда не недооценивайте веб-жилет. Хотя он и не обеспечивает защиту от космических угроз, его низкая цена и надежная защита делают его полезным для защиты от
```suggestion
tips-dataset-34 = Будучи предателем, никогда не недооценивайте тактический жилет. Хотя он и не обеспечивает защиту от космоса, его низкая цена и надежная защита делают его полезным для защиты от врагов с огнестрельным оружием.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-36 = В качестве предателя будьте осторожны при использовании вестина из набора химического синтеза. Если кто-то проверит вашу станцию, они легко могут вас разоблачить.
```suggestion
tips-dataset-36 = Будучи предаталем, будьте осторожны при использовании вестина из набора химического синтеза. Если кто-то проверит ваш ХимМастер, он сможет легко вас разоблачить.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-37 = В качестве предателя помните, что силовые ловушки будут издавать громкий звук и привлекут внимание экипажа после длительной работы.
Силовые ловушки? Чево? Может быть взрывчатка? А ещё ты пропустил 38 и 40 советы

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-39 = Для Предателя обезвоженные карпы могут служить средством для массового поражения. Если похлопать их перед регидратацией, они могут выступить в качестве отвлекающего маневра.
Погладить? Чё?

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-41 = Для Ядерного Оперативника необходимо действовать сообща. Хотя ваше оборудование надежно, коллеги-оперативники значительно повысит вашу шансы на спасение: они могут оттащить вас от о
```suggestion
tips-dataset-41 = Ядерным Оперативникам необходимо действовать сообща. Хоть ваше оборудование и надежно, коллеги-оперативники значительно повысят ваши шансы на спасение: они могут оттащить вас от опасности и обеспечить огневую поддержку.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-44 = Как противник, учитывайте важность уничтожения телекоммуникационных линий. Людям будет значительно сложнее вызвать вас, если они не смогут это сделать эффективно.!
```suggestion
tips-dataset-44 = Как антагонист, учитывайте важность уничтожения телекоммуникационных серверов. Людям будет значительно сложнее сообщить о вас, если они не смогут сделать это эффективно!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-45 = Проверьте свою гарнитуру, чтобы узнать доступные радиоканалы и способы связи с ними.
```suggestion
tips-dataset-45 = Проверьте свою гарнитуру (Shift + ЛКМ по умолчанию), чтобы узнать доступные радиоканалы и способы их использования.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-46 = Как специалист по спасению, всегда имейте при себе GPS и записывайте координаты станции на случай потери связи в космосе.
```suggestion
tips-dataset-46 = Будучи утилизатором, всегда имейте при себе GPS и записывайте координаты станции на случай  потери в космосе.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-47 = Как специалист по спасению, вы можете использовать протокинетический ускоритель для перемещения в пространстве в экстренной ситуации. Будьте wary, поскольку он не очень эффективен.
```suggestion
tips-dataset-47 =  Будучи утилизатором, вы можете использовать протокинетический ускоритель для перемещения в пространстве в экстренной ситуации. Будьте осторожны, поскольку он не очень эффективен.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-48 = Как специалист по спасению, помните о важности добычи руды. Ее можно продать или использовать для строительства, а также для разработки необычных технологий.
```suggestion
tips-dataset-48 = Будучи утилизатором, помните о важности добычи руды. Ее можно продать или использовать для строительства и разработки необычных технологий.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-135 = Вместо того, чтобы подбирать еду, вы можете нажать альт + клик для ее употребления. Это также работает для мышей и других существ без рук.
```suggestion
tips-dataset-135 = Вместо того, чтобы подбирать еду, вы можете использовать Alt + клик (по умолчанию) для ее употребления. Это также работает для мышей и других существ без рук.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-131 = Вы можете варить осколки стекла в стеклянные листы.
```suggestion
tips-dataset-131 = С помощью сварки вы можете превратить осколок в лист стекла
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-130 = Зомби очень уязвимы к урону от тепла, что делает сварочные инструменты и лазерные пистолеты крайне эффективными против них.
```suggestion
tips-dataset-130 = Зомби очень уязвимы к термическому урону, что делает сварочные инструменты и лазерное оружие крайне эффективными против них.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-129 = Сварка без соответствующей защитной eyewear может вызвать повреждение глаз, которое необходимо лечить окуляриной.
```suggestion
tips-dataset-129 = Сварка без соответствующей защиты глаз может вызвать их повреждение, которое необходимо лечить окулином.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-125 = Щели спасательных инструментов могут использоваться для открытия электрических дверей.
```suggestion
tips-dataset-125 = Челюсти жизни могут использоваться для открытия запитанных дверей.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-124 = Некоторые оружия, такие как ножи и шивы, имеют высокую скорость атаки.
```suggestion
tips-dataset-124 = Некоторое оружие, такое как ножи и заточки, имеет высокую скорость атаки.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-120 = Вы можете оглушить гранатные пингвины, что даст вам ценное время, чтобы их убить.
```suggestion
tips-dataset-120 = Вы можете оглушить пингвинов-смертников, что даст вам ценное время, чтобы их убить.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-121 = Вы можете кликнуть на название предмета, чтобы его подобрать в меню правой кнопки мыши, вместо того чтобы наводить курсор на предмет и затем выбирать "подобрать".
```suggestion
tips-dataset-121 = В контекстном меню правой кнопки мыши вы можете кликнуть на название предмета, вместо того чтобы наводить курсор на предмет и затем выбирать "подобрать".
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-119 = У большинства взрывных устройств есть регулируемый таймер, который можно настроить в меню правой кнопки мыши. Сюда входят и гранатные пингвины!
```suggestion
tips-dataset-119 = У большинства взрывных устройств есть регулируемый таймер, который можно настроить в контекстном меню правой кнопки мыши. Сюда входят и пингвины-смертники!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-112 = При взаимодействии с охраной вы можете часто добиться полной отмены своего приговора через сотрудничество и обман.
```suggestion
tips-dataset-112 = При взаимодействии со службой безопасности вы часто можете добиться полной отмены своего приговора через сотрудничество и обман.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-106 = Газовые маски Синдиката обеспечивают как защиту при сварке, так и блокируют вспышки. Подумайте дважды, прежде чем пытаться ослепить Ядерного Оператива
```suggestion
tips-dataset-106 = Противогазы Синдиката обеспечивают защиту от сварок и впышек. Подумайте дважды, прежде чем пытаться ослепить Ядерного Оперативника
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-105 = То, что работа не может быть предателем в начале раунда, не значит, что он никогда не станет предателем.
```suggestion
tips-dataset-105 = То, что определенная профессия не может быть предателем в начале раунда, не значит, что он а никогда не станет предателем.
```
Шут его знает, на что заменить профессию

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-104 = Скорость почти все в бою. Использование жестких костюмов только ради их брони обычно плохая идея, если сопротивление, которое они предоставляют, не связано с боем, или если вы не п
```suggestion
tips-dataset-104 = Скорость - почти все в бою. Использование тяжелых костюмов только ради их брони обычно плохая идея, если защита, которую они предоставляют, не связано с боем, или если вы не планируете лезть вперед.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-102 = Вы можете положить напалм в водяной бак рюкзака, чтобы создать огнемет.
```suggestion
tips-dataset-102 = Вы можете заправить ранцевый водяной резервуар напалмом и флогистоном в пропорции 9:1 соответственно, чтобы создать огнемет.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-101 = Вы можете бросать изготовленные болосы в людей, чтобы замедлить их, давая вам возможность легче их убить или убежать.
```suggestion
tips-dataset-101 = Вы можете бросать изготовленные болы в людей, чтобы замедлить их, давая вам возможность легче их убить или убежать.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-100 = Все формы токсического урона довольно сложно лечить, и обычно для этого требуются химикаты или другие неудобные методы. Вы можете использовать это в свою пользу в бою.
```suggestion
tips-dataset-100 = Все формы токсичного урона довольно сложно лечить, и обычно для этого требуются химикаты или другие неудобные методы. В бою вы можете использовать это в свою сторону.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-98 = Вы можете создать копья с помощью армированного стекла, плазменного стекла или осколков уранового стекла для увеличения их урона.
```suggestion
tips-dataset-98 = Вы можете создать копья с помощью осколков армированного, плазменного и уранового стекол.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-96 = В экстренной ситуации помните, что вы можете создать импровизированное оружие! Бейсбольная бита или копье могут легко стать разницей между тем, чтобы отразить нападение или погибнут
```suggestion
tips-dataset-96 = В экстренной ситуации помните, что вы можете создать импровизированное оружие! Бейсбольная бита или копье могут стать решающим фактором между тем, чтобы отразить нападение или погибнуть от рук врага.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-95 = В экстренной ситуации вы всегда можете положиться на огнеупорные костюмы и аварийные скафандры EVA; они всегда появляются в своих соответствующих шкафчиках. Они могут быть неудобным
```suggestion
tips-dataset-95 = В экстренной ситуации вы всегда можете положиться на огнеупорные костюмы и аварийные скафандры EVA; они всегда появляются в своих соответствующих шкафчиках. Они могут быть неудобными для движения, но спасут вам жизнь в опасной ситуации.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-92 = В службе эксплуатации есть оборудование, которое случайным образом меняется каждый раунд. Посмотрите вокруг и посмотрите, что стоит использовать.
```suggestion
tips-dataset-92 = В технических помещениях есть вещи, которые случайным образом меняются каждый раунд. Осмотритесь и определите, что будет полезно для вас.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-90 = Если вам что-то нужно из другого отдела, попробуйте спросить! Эта игра не одиночная, и вы будете удивлены, что сможете сделать вместе!
```suggestion
tips-dataset-90 = Если вам нужно что-то из другого отдела, попробуйте спросить! Эта многопользовательская игра, и вы будете удивлены тем, что сможете сделать вместе!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-89 = Вы быстро потеряете интерес к игре, если будете играть, чтобы выигрывать и убивать. Если вы заметите, что делаете это, сделайте шаг назад и поговорите с людьми — это намного лучше!
```suggestion
tips-dataset-89 = Вы быстро потеряете интерес к игре, если будете играть, чтобы выигрывать и убивать - "на победку". Если вы заметите, что делаете это, сделайте шаг назад и поговорите с людьми — это намного лучше!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-87 = В роли Врача, Химика или Главного Врача вы можете использовать хлоралоктазин для нефатального седирования буйных пациентов.
```suggestion
tips-dataset-87 = Будучи врачом, химиком или главным врачом, вы можете использовать хлоральгидрат для нелетального усмирения буйных пациентов.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-86 = В роли Химика, как только вы сделали все, что нужно, не бойтесь создавать больше забавных реагентов. Пробовали ли вы дезоксидифедрин или ликсид?
```suggestion
tips-dataset-86 = Будучи химиком, как только вы сделали все, что нужно, не бойтесь создавать больше забавных реагентов. Пробовали ли вы дезоксидифедрин или ликосид?
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-85 = В роли Врача помните, что анализатор здоровья можно использовать, если вы потеряли свой PDA. Однако у него есть батарея, и если она быстро разрядится, вы можете попросить ученых нап
```suggestion
tips-dataset-85 = Будучи врачом, помните, что анализатор здоровья можно использовать, если вы потеряли свой КПК. Однако у него есть батарея, и если она быстро разрядится, вы можете попросить ученых напечатать лучшую батарею для вас!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-84 = В роли Врача будьте осторожны при помещении рептилий в крио-поды. Они получат много дополнительного урона от холода, но вы можете смягчить это с помощью медикаментов от ожогов или л
```suggestion
tips-dataset-84 = Будучи врачом, будьте осторожны при помещении унатхов в криокапсулы. Они получат много дополнительного урона от холода, но вы можете смягчить это с помощью медикаментов от ожогов или лепоразина.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-83 = В роли Врача не недооценивайте свои крио-поды! Они лечат почти все виды повреждений, что делает их очень полезными, когда вы перегружены или нужно срочно вылечить кого-то.
```suggestion
tips-dataset-83 = Будучи врачом, не недооценивайте свои криокапсулы! Они лечат почти все виды повреждений, что делает их очень полезными, когда вы перегружены или нужно срочно вылечить кого-то.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-82 = В роли Врача следите за тем, чтобы не передозировать своих пациентов, особенно если кто-то другой уже находился на месте происшествия. Передозировка часто является смертельной для п
```suggestion
tips-dataset-82 = Будучи врачом, следите за тем, старайтесь не допустить передозировки у своих пациентов, особенно если кто-то другой уже вводил реагенты. Передозировка часто является смертельной для пациентов в критическом состоянии!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-81 = В роли Ученого вы можете создавать киборгов, используя позитронные мозги и шасси; они так же полезны, как новый член экипажа.
```suggestion
tips-dataset-81 = Будучи ученым, вы можете создавать киборгов, используя позитронные мозги и шасси; они так же полезны, как новый член экипажа.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-80 = В роли Ученого вы можете использовать улучшенные версии машин, чтобы увеличить их эффективность. Это может значительно улучшить определенные машины; спасатели будут вам благодарны,
```suggestion
tips-dataset-80 = Будучи ученым, вы можете использовать улучшенные версии машин, чтобы увеличить их эффективность. Это может значительно улучшить определенные машины; утилизаторы будут благодарны вам, если вы обновите их переработчик руды!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-79 = В роли Ученого вы можете попробовать случайные действия с артефактом, пока сканер находится в режиме охлаждения, чтобы значительно ускорить процесс экстракции.
```suggestion
tips-dataset-79 = Будучи ученым, вы можете попробовать случайные действия с артефактом, пока сканер находится в режиме охлаждения, чтобы значительно ускорить процесс его активации.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-78 = В роли Капитана постарайтесь быть активным и патрулировать станцию. Оставаться в рубке может быть заманчиво, но вы просто наклеите на себя большую мишень!
```suggestion
tips-dataset-78 = Будучи капитаном, постарайтесь быть активным и гулять по станции. Оставаться на мостике может быть заманчиво, но вы просто наклеите на себя большую мишень!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-77 = В роли Капитана у вас есть абсолютный доступ и контроль над станцией, но это не значит, что если вы станете ужасным человеком, это не приведет к мятежу.
```suggestion
tips-dataset-77 = Будучи капитаном, у вас есть полный доступ и контроль над станцией, но это не значит, что если вы станете ужасным человеком, это не приведет к мятежу.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-76 = В роли Капитана всегда берите с собой ядерный диск и указатель каждый смену. Хорошая идея — передать один из этих предметов другому руководителю, которому вы доверяете, чтобы он его
```suggestion
tips-dataset-76 = Будучи капитаном, всегда берите с собой диск ядерной авторизации и пинпоинтер каждыую смену. Хорошая идея — передать один из этих предметов другому руководителю, которому вы доверяете.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-75 = В роли Капитана вы являетесь одной из самых высокоприоритетных целей на станции. Вам следует беспокоиться обо всем — от революций до ядерных оперативников и предателей, которые могу
```suggestion
tips-dataset-75 = Будучи капитаном, вы являетесь одной из самых приоритетных целей на станции. Вам следует беспокоиться обо всем — от революций до ядерных оперативников и предателей, которые могут попытаться отобрать ваш антикварный лазерный пистолет или жизнь.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-49 = Как специалист по спасению, рассмотрите возможность запроса у научного отдела тросового ружья для эффективного извлечения предметов из обломков!
```suggestion
tips-dataset-49 = Будучи утилизатором, рассмотрите возможность запроса у научного отдела крюк-пушки для эффективного сбора предметов на обломках!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-50 = Как специалист по спасению, возможно, стоит попросить крюк-кошку для подъема на обломки и, если вы окажетесь в космосе, чтобы избежать использования протокинетического ускорителя.
```suggestion
tips-dataset-50 = Будучи утилизатором, возможно, стоит попросить крюк-пушку для подъема на обломки и, если вы окажетесь в космосе, чтобы избежать использования протокинетического ускорителя.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-52 = Как специалист по спасению, рассмотрите сотрудничество с грузовыми техниками, которые могут предоставить вам редкие и полезные предметы, такие как лазерные пушки и строительные мате
```suggestion
tips-dataset-52 = Будучи утилизатором, рассмотрите сотрудничество с грузчиками, которые могут предоставить вам редкие и полезные предметы, такие как лазерное оружие и строительные материалы для шаттлов.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-53 = Как грузчик, подумайте о запросе у научного отдела Ripley APLU. В сочетании с гидравлическим зажимом это облегчит захват ценных объектов.
```suggestion
tips-dataset-53 = Будучи грузчиком, подумайте о запросе у научного отдела Рипли. В сочетании с гидравлической клешней это облегчит захват ценных объектов.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-54 = Как грузчик, старайтесь поддерживать достаточный запас материалов. Они крайне необходимы ученым и инженерам для быстрого доступа.
```suggestion
tips-dataset-54 = Будучи грузчиком, старайтесь поддерживать достаточный запас материалов. Они крайне необходимы ученым и инженерам.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-55 = Как грузчик, обладая избыточными деньгами, рассмотрите азартные игры — иногда можно получить больше денег, чем изначально.
```suggestion
tips-dataset-55 = Будучи грузчиком, и обладая избыточными деньгами, рассмотрите возможность покупки лотереи  — иногда можно получить больше денег, чем изначально.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-56 = Как ггрузчик, помните о возможности заказа оружия в экстренной ситуации. Дополнительная огневая мощь может стать решающим фактором для вашей команды.
```suggestion
tips-dataset-56 = Будучи грузчиком, помните о возможности заказа оружия в экстренной ситуации. Дополнительная огневая мощь может стать решающим фактором для вашей команды.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-57 = Как бармен, используйте циркулярную пилу для хранения своего ружья.
```suggestion
tips-dataset-57 = Будучи барменом, используйте свой шкафчик для хранения ружья.
```
ЫХЫХЫХХЫХЫ,ТАМ БУКВАЛЬНО У ОФФОВ ПИЛА

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-58 = Как бармен, экспериментируйте с уникальными напитками. Пробовали ли вы сделать кровь демона?
```suggestion
tips-dataset-58 = Будучи барменом, экспериментируйте с уникальными напитками. Пробовали ли вы сделать кровь демона?
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-74 = В роли Инженера вы можете использовать плазменное стекло для усиления области и предотвращения радиации. Урановое стекло также может быть использовано для предотвращения радиации.
```suggestion
tips-dataset-74 = Будучи инженером, вы можете использовать плазменное стекло для усиления области и предотвращения радиации. Урановое стекло также может быть использовано для предотвращения радиации.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-59 = Как ботаник, используйте мутацию и скрещивание растений для создания более мощных продуктов с высоким урожаем.
```suggestion
tips-dataset-59 = Будучи ботаником, используйте мутации и скрещивание растений для создания более мощных продуктов с высоким урожаем.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-60 = Как клоун, разнообразьте свои трюки. Одноаспектные представления не привлекают зрителей.
```suggestion
tips-dataset-60 = Будучи клоуном, разнообразьте свои трюки. Одинаковые представления не привлекают зрителей.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-61 = Как клоун, даже потеря банановой кожуры и мыла не помешает подсунуть КПК. Сигнальте!
```suggestion
tips-dataset-61 = Будучи клоуном, помните, что даже потеря банановой кожуры и мыла не помешает подсунуть КПК. ХОНК!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-62 = В роли Шефа ваш нож может служить оружием в экстренной ситуации.
```suggestion
tips-dataset-62 = Будучи поваром, помните, что ваш нож может служить оружием в экстренной ситуации.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-73 = В роли Инженера всегда дважды проверяйте, когда вы настраиваете сингулярность. Потерять её проще, чем вы думаете!
```suggestion
tips-dataset-73 =Будучи инженером, всегда дважды проверяйте сдерживающее поле Сингулярности. Потерять её проще, чем вы думаете!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-72 = В роли Инженера вы можете электризовать решетки, поместив под ними питаемые кабели.
```suggestion
tips-dataset-72 = Будучи инженером, вы можете электризовать решетки, поместив под ними питаемые кабели.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-71 = В роли Инженера вы можете восстановить треснувшие окна, используя сварочный инструмент при выключенном боевом режиме.
```suggestion
tips-dataset-71 = Будучи инженером, вы можете восстановить треснувшие окна, используя сварочный инструмент при выключенном боевом режиме.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-70 = В роли Атмосферного техника постарайтесь противостоять искушению создавать бомбочки для Ядерных Оперативов, если только вы не находитесь в безвыходной ситуации. Это часто приводит к
```suggestion
tips-dataset-70 = Будучи атмосферным техником, постарайтесь противостоять искушению создавать бомбы("лимитки"), если только вы не находитесь в безвыходной ситуации. Это часто приводит к значительному количеству ненужного огня по своим!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-69 = В роли Атмосферного техника ваш проектор ATMOS холофана блокирует газы, позволяя при этом проходить объектам. С его помощью вы можете быстро локализовать утечки газа, пожары и пробо
```suggestion
tips-dataset-69 =Будучи атмосферным техником, используйте атмос-голопороектор для блокировки газов, позволяя при этом проходить объектам. С его помощью вы можете быстро локализовать утечки газа, пожары и пробоины корпуса.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-68 = В роли Детектива вы можете более эффективно преследовать преступников, используя данные о отпечатках пальцев и ДНК, полученные из судебных сканирований объектов, с которыми, скорее
```suggestion
tips-dataset-68 = Будучи детективом, вы можете более эффективно расследовать преступления, используя данные о отпечатках пальцев и ДНК, полученные с помощью криминалистического сканера. Стоит сканировать лишь те предметы, с которыми, вероятно, взаимодействовал злоумышленник.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-67 = В роли Офицера службы безопасности помните, что корреляция не равна причинности. Кто-то мог оказаться не в том месте и не в то время!
```suggestion
tips-dataset-67 = Будучи офицером службы безопасности, помните, что корреляция не является  причинно-следственной связью. Кто-то мог оказаться не в том месте и не в то время!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-66 = В роли Офицера службы безопасности общайтесь и координируйте действия с коллегами, используя радиоканал безопасности, чтобы избежать путаницы.
```suggestion
tips-dataset-66 = Будучи офицером службы безопасности, общайтесь и координируйте действия с коллегами, используя радиоканал безопасности во избежание путаницы.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-65 = В роли Юриста постарайтесь договориться с Надзирателем, если приговоры кажутся слишком строгими для преступления.
```suggestion
tips-dataset-65 = Будучи юристом, постарайтесь договориться со смотрителем, если приговоры кажутся вам слишком строгими.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-64 = В роли Мима ваша клятва молчания — это ваша сила. Нарушение её лишает вас способностей и чести.
```suggestion
tips-dataset-64 = Будучи мимом, помните, что ваша клятва молчания — это ваша сила. Нарушение её лишает вас способностей и чести.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/tips.ftl
> +tips-dataset-63 = В роли Шефа вы можете тайком добавлять жидкости в свои блюда. Как предатель, немного аматоксина или другого яда может сильно раздражать команду!
```suggestion
tips-dataset-63 = Будучи поваром, вы можете тайком добавлять жидкости в свои блюда. Если вы являетесь предателем, немного аматоксина или другого яда может сильно досаждать экипаж
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/traitor/traitor-codes-component.ftl
> +traitor-codes-none = Неизвестных кодовых слов нет
```suggestion
traitor-codes-none = Известных кодовых слов нет
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/view-variables.ftl
> +vv-sound-loop = Loop
```suggestion
vv-sound-loop =Зациклить
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/voting/managers/vote-manager.ftl
> +ui-vote-votekick-title = { $initiator }  вызвал голосование для пользовател: { $targetEntity }. Причина: { $reason }
```suggestion
ui-vote-votekick-title = { $initiator }  начал голосование для исключения пользователя: { $targetEntity }. Причина: { $reason }
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/voting/managers/vote-manager.ftl
> +ui-vote-votekick-success = Голосование за { $target } преуспевший. Выберите причину голосования: { $reason }
```suggestion
ui-vote-votekick-success = Голосование за исключение { $target } успешно. Выберите причину голосования: { $reason }
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/voting/managers/vote-manager.ftl
> +ui-vote-votekick-server-cancelled = Голосование за { $target } было отменено сервером.
```suggestion
ui-vote-votekick-server-cancelled = Голосование за исключение { $target } было отменено сервером.
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/voting/managers/vote-manager.ftl
> +ui-vote-votekick-not-enough-eligible = Недостаточно онлайн-избирателей, имеющих право голоса, для начала голосования: { $voters }/{ $requirement }
```suggestion
ui-vote-votekick-not-enough-eligible = Недостаточно избирателей онлайн для начала голосования: { $voters }/{ $requirement }
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/voting/ui/vote-call-menu.ftl
> +  Злоупотребление системой Кикнуть может привести к бессрочной блокировке!
```suggestion
  Злоупотребление системой исключения может привести к бессрочной блокировке!
```

2024-11-16 23:27 UTC, Oguz0k220 commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-hints.ftl
> +artifact-trigger-hint-medical = Терапевтические химикаты
```suggestion
artifact-trigger-hint-medical = Медицинские реагенты
```

2024-11-16 23:30 UTC, Oguz0k220 commented
Вроде всё. Сорямба за минусы вместо тире, спать хочу - лень исправлять :c
Мейби завтра поправлю.

2024-11-16 23:39 UTC, Poeeno commented
Нечего, спасибо за поправки 🤝. Днем посмотрю что да как

вс, 17 нояб. 2024 г., 02:30 Oguz0k220 ***@***.***>:

> Вроде всё. Сорямба за минусы вместо тире, спать хочу - лень исправлять :c
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/imperial-space/SS14-public/pull/43#issuecomment-2480849590>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT42ZNRTHFYHRXIZJFEHWV32A7ISXAVCNFSM6AAAAABR3TORTOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBQHA2DSNJZGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-19 23:11 UTC, merged