Отображение должностей в рации. Обновлено под апстрим
imperial-space/SS14-public pull request #49
Opened 2024-11-21 23:45 UTC by Requiem4soul

## About the PR
**Обновление отображение должностей в рации**

## Why / Balance
Для баланса вселенной. **Обновление для старой версии**

## Technical details
**Всё ещё можно создать прототип карты, он будет в словаре. Максимально оптимизировано.**

![изображение](https://github.com/user-attachments/assets/4a71360f-3cbf-4f81-8b05-1af6ed9ae361)

2024-11-28 19:08 UTC, CREAsTIVE requested changes
В следующий раз пожалуйста создавай отдельную ветку.

На текущий момент у тебя система полностью зависит от локализации. Я предлагаю такой вариант:

В yml хранится что то такое:
```yml
- type: customJobColor
  id: Detective # Такое же, как и id профессии
  color: red
  
- type: customJobColor
  id: CentralCommandOfficial
  color: blue
  bold: true # Доп параметры опционально
```

После в коде просто получаем id профессии и через `_protoManager.Index<CustomJobColor>(jobId)` (что так же твой любимый O(1)) получаем всю необходимую информацию о форматировании профессии.

Тогда никакого ручного кеширования делать будет не надо, никакой зависимости от локализации тоже не будет, и можно будет легко вводить новые параметры.

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    private static Dictionary<string, string> SaveColorForJob = new Dictionary<string, string>();
Если уж и кешируешь значения прототипов, то храни хотя бы `Dictionary<string, ProtoId<IdColorAndJobPrototype>>`. А вообще в общем сообщении глянь другое решение.

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    private static readonly Dictionary<string, string> JobTranslations = new()
Долой хардкод

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        var prototypes = IoCManager.Resolve<IPrototypeManager>().EnumeratePrototypes<IdColorAndJobPrototype>();
```suggestion
        var prototypes = _prototypeManager.EnumeratePrototypes<IdColorAndJobPrototype>();
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +                playerJob = Regex.Replace(playerJob, @"[-–—−]", " ");
Регулярки для таких задач в целом... meh, но если и используешь их, то инициализируй хотя бы паттерн статически:
```
static Regex NameFixer = new(@"[-–—−]")
...
NameFixer.Replace(playerJob, " ")
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (jobPlayer != null)
Инверсируй условия:
```suggestion
        if (jobPlayer is null) return "lime"; // Работа не определена
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    public string? GetColorPlayer(string? jobPlayer)
Не вижу ни одной причины возвращать нуллейбл. По идее этот метод должен уже точно определять цвет профессии, что бы не было лишних null проверок
```suggestion
    public string GetColorPlayer(string? jobPlayer)
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +            }
Инвёрс условия:
```suggestion
            // Если должность не найдена
            if (!SaveColorForJob.ContainsKey(normalizedJob)) return "lime";
            
            // Возвращаем цвет должности
            string color = SaveColorForJob[normalizedJob];
            return color;
```

(А вообще лучше сразу избавиться от двойного поиска:
```suggestion
return SaveColorForJob.TryGetValue(normalizedJob, out var color) ? color : "lime"
```
)

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +                return "lime";
Дефолтный цвет стоит вынести в константу

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        string? nameColorPlayer = GetColorPlayer(nameJobPlayer);
```suggestion
        string nameColorPlayer = GetColorPlayer(nameJobPlayer);
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if ((nameColorPlayer != null) && (nameJobPlayer != null))
Убрать условия, т. к. эти поля более не могут быть nullable

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +using Content.Server.Imperial.Radio;
```suggestion
using Content.Server.Imperial.Radio; // Imperial RadioPlayerAndJob
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +    [Dependency] private readonly JobPlayerAndColor _jobPlayer = default!;
```suggestion
    [Dependency] private readonly JobPlayerAndColor _jobPlayer = default!; // Imperial RadioPlayerAndJob
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    public string? GetJobPlayer(EntityUid uid)
Нуллейбл и так не возвращается
```suggestion
    public string GetJobPlayer(EntityUid uid)
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (_idCardSystem.TryFindIdCard(uid, out var id))
Инверсия условий!!!

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +            if (playerJob != null)
Инверсия условий!!

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        string? nameJobPlayer = GetJobPlayer(uid);
```suggestion
        string nameJobPlayer = GetJobPlayer(uid);
```

2024-11-28 19:08 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (nameJobPlayer != null)
Более не обходимо

2024-11-29 09:32 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    private static Dictionary<string, string> SaveColorForJob = new Dictionary<string, string>();
Пу-пу-пу, привет! Сейчас буду объяснять
`SaveColorForJob ` создан для хранения **уже вычисленных результатов (string)**. Это позволяет избавиться от повторных поисков уже найденных значений, что экономит производительность и считается важным в сетевых приложениях, где важна оптимизация. (мемоизация в программировании)
Так же использование строк в качестве ключей и значений минимизирует затраты ресурсов. При добавлении абстракции `ProtoId` увеличиться сложность и может повлиять на время выполнения операции, в чём и была изначальная задумка хэш таблица с мемоизацией результатов.

Крайне ошибочно было считать что тут хранятся прототипы. **Данный словарь отвечает именно за кэширование уже найденных результатов для повторном использовании данных. У него совершенно иная функция**

2024-11-29 09:34 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    private static readonly Dictionary<string, string> JobTranslations = new()
Да нет, ты чего. Мемоизация - это база в динамическом и сетевом программировании. Буквально оптимизация. Скорее всего ты просто не совсем понял для чего это нужно, выше описал

2024-11-29 09:43 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +                playerJob = Regex.Replace(playerJob, @"[-–—−]", " ");
Обрабатывать входные результаты в данном случае обязательно, так как при форматировании текста функцией офов, такие значения будут ломать вывод в целом. Так же данное часто используется для защиты от SQL инъекций и вполне себе нормальная практика. 

По поводу почему тут как раз не стоит использовать `static`:
Регулярное выражение в данном месте используется в исключительно единственном методе и только при условии найденной работы. Для других значений оно не нужно. Создание `static` тут лишь увеличит сложность кода (О - которая)
Использование `static` тут имело смысл только если оно используется в нескольких местах или вызывается многократно раз. Поэтому дополнительное усложнение не оправдано.
Так же напомню что компилятор уже оптимизирует локально инициализированные строки.

Объяснил, поэтому закрываю

2024-11-29 09:46 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (jobPlayer != null)
Не, креатив, я настоятельно тебя попрошу вникнуть в то, что делает код. Ты буквально просишь создать ошибку уже.
`!=` это наоборот не равно `null`. У тебя `is` будет аналогом `==`

**Креатив, я прошу взглянуть на код внимательно и понять принцип его работы. Нельзя предлагать такие изменения, которые наоборот ломают код. Будь пожалуйста внимателен** 

Закрываю с пометкой ### "НИ В КОЕМ СЛУЧАЕ НЕЛЬЗЯ ТАК ДЕЛАТЬ!"

2024-11-29 09:48 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    public string? GetColorPlayer(string? jobPlayer)
Мышка в рацию сказала сквик, у неё функция по поиску jobTitle через pda выдаст null, так как у мыши её нет

Не использовать тут string? - будет создавать фатальные ошибки...

### Креатив, очень прошу быть вдумчивым в ревью, чтобы не предлагать людям то, что сломает наоборот код

Закрываю с меткой ### "НИ В КОЕМ СЛУЧАЕ ТАК НЕ ДЕЛАТЬ!"

2024-11-29 09:50 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        string? nameColorPlayer = GetColorPlayer(nameJobPlayer);
Объяснял выше, с пометкой ### "НИ В КОЕМ СЛУЧАЕ ТАК НЕ ДЕЛАТЬ!"

2024-11-29 09:55 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        var prototypes = IoCManager.Resolve<IPrototypeManager>().EnumeratePrototypes<IdColorAndJobPrototype>();
Выше объяснял что словарь отвечает за мемоизацию уже рассчитанных результатов. Иная функция.

Закрываю, так как выше объяснял

2024-11-29 09:58 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +                playerJob = Regex.Replace(playerJob, @"[-–—−]", " ");
Как раз таки такое компилятор вполне может и пропустить. В шарпе нет понятий конст-експр конструкторов. Проблема в том, что ты инициализируешь каждый раз новую регулярку из строки, а значит дерево регулярки тут как раз таки строится каждый раз заново (если конечно шарп компилятор этого не заметил, что вряд-ли)

2024-11-29 09:59 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if ((nameColorPlayer != null) && (nameJobPlayer != null))
Данные проверки являются стандартными и активно используются офами в их оригинальном коде. Данные проверки необходимы для обработки ошибок и багов.

Пример из ChatSystem метод TrySendInGameICMessage:
`if (HasComp<GhostComponent>(source))
        {
            // Ghosts can only send dead chat messages, so we'll forward it to InGame OOC.
            TrySendInGameOOCMessage(source, message, InGameOOCChatType.Dead, range == ChatTransmitRange.HideChat, shell, player);
            return;
        }

        if (player != null && !_chatManager.HandleRateLimit(player))
            return;

        // Sus
        if (player?.AttachedEntity is { Valid: true } entity && source != entity)
        {
            return;
        }

        if (!CanSendInGame(message, shell, player))
            return;`
            
Закрываю

2024-11-29 10:02 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (jobPlayer != null)
Посмотри внимательно на чендж реквест: я перенёс `return` в это условие

А я и не отрицаю. Инверс условий это техника, что позволяет сильно сократить вложенность. 
В твоём коде:

```cs
if (validate) {
  doSomething();
  if (validate) {
    doMore();
  }
  else {
    errorHandle();
  }
}
else {
  errorHandle();
}
```

Когда я настоятельно рекомендую:

```
if (!validate) errorHandle();
doSomething();
if (!validate) errorHandle();
doMore();
```

2024-11-29 10:06 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    private static Dictionary<string, string> SaveColorForJob = new Dictionary<string, string>();
Вот только сами офицалы **настоятельно** не рекомендуют заниматься ручным кешированием. Данная разница в производительности (МИНИМАЛЬНАЯ прошу заметить) не стоит перед "чистотой кода". + Я предложил такой же по скорости вариант, но без ручного кеширования, см основной коммент

2024-11-29 10:06 UTC, Requiem4soul commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +    [Dependency] private readonly JobPlayerAndColor _jobPlayer = default!;
В зависимостях и using мы не указываем лицензию на код.
Пример с системы психоза:
`using Content.Shared.Imperial.ICCVar;`
`public sealed class MassPsychosisRule : StationEventSystem<MassPsychosisRuleComponent>
{
    [Dependency] private readonly PsychosisSystem _psychosis = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;`
    
    `

2024-11-29 10:07 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        var prototypes = IoCManager.Resolve<IPrototypeManager>().EnumeratePrototypes<IdColorAndJobPrototype>();
Не понял, тут я предлагаю не ресолвить заного прототайп менеджер, а использовать депенденси. В чём тут мемоизация?

2024-11-29 10:09 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    public string? GetColorPlayer(string? jobPlayer)
Мышка в рацию сказала сквик, и эта функция должна вернуть цвет игрока (исходя из имени), а не *может быть* цвет игрока. Если мышка сказала сквик, то пусть уж эта функция возвращает как раз таки дефолтный цвет (что я так же отмечал в ревью)

2024-11-29 10:10 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        string? nameColorPlayer = GetColorPlayer(nameJobPlayer);
Объяснил выше)

2024-11-29 10:10 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (_idCardSystem.TryFindIdCard(uid, out var id))
Данное ясно выражает намерение: "Если ID-карта найдена, выполняем дальнейшие действия". Инверсия этого условия приведёт к добавлению лишнего отрицания и увеличению ненужной нагрузки.

Мы не можем позволить себе тут сделать ранний выход, так как задача стоит в том, что для всех не найденных id и у тех, кто её в целом иметь не может, должно отображаться должность "Неизвестно"

Закрываю

2024-11-29 10:11 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if ((nameColorPlayer != null) && (nameJobPlayer != null))
Данное изменение предложено на основе того, что мы отказываемся от nullable.

2024-11-29 10:11 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +            if (playerJob != null)
Аналогично выше, закрываю, так как нам необходимо обрабатывать такие исключения

2024-11-29 10:12 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        string? nameJobPlayer = GetJobPlayer(uid);
Опять предложение критической ошибки. Закрываю с пометкой ### "НИ В КОЕМ СЛУЧАЕ ТАК НЕ ДЕЛАТЬ!"

Закрываю, выше объяснено почему такое будет приводить к критической ошибке

2024-11-29 10:12 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +        if (nameJobPlayer != null)
Закрываю, так как выше объяснял

2024-11-29 10:13 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +    public string? GetJobPlayer(EntityUid uid)
Опять же вызов критической ошибки. Выше объяснялось. Закрываю с пометкой ### "НИ В КОЕМ СЛУЧАЕ ТАК НЕ ДЕЛАТЬ!"

2024-11-29 10:14 UTC, Requiem4soul commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +using Content.Server.Imperial.Radio;
Было показано на разработке психоза, что using и зависимости у нас (как и у других) не помечаются лицензией, так как лицензия вешается на саму реализацию, а не на использование какого-то метода

2024-11-29 10:16 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +            }
Отсутствие обработки ошибок будет приводить к тому, что ошибки не будут обрабатываться. Так же в jobPlayer мы уже задаём значения для тех работ, которые невозможно найти или их нет

Закрываю

2024-11-29 10:18 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +                return "lime";
это дефолтный цвет, используемый исключительно в этом конкретном методе. Его значение понятно из контекста и не используется повторно в других частях проекта. Неоправданный вынос константы для единоразового использования в методе.

Закрываю

2024-11-29 10:21 UTC, CREAsTIVE commented on Content.Server/Imperial/Radio/JobPlayerAndColor.cs
> +            }
Мой изменённый код полностью идентичен твоему коду и работает точно так же, НО не совершает поиск по словарю дважды (что как раз таки и вредит оптимизации)

2024-11-29 10:21 UTC, CREAsTIVE commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +using Content.Server.Imperial.Radio;
Я так же думал, однако меня позже миртон просил даже юзинги помечать меткой империала. Увы

2024-11-29 10:22 UTC, Requiem4soul commented
> В следующий раз пожалуйста создавай отдельную ветку.
> 
> На текущий момент у тебя система полностью зависит от локализации. Я предлагаю такой вариант:
> 
> В yml хранится что то такое:
> 
> ```yaml
> - type: customJobColor
>   id: Detective # Такое же, как и id профессии
>   color: red
>   
> - type: customJobColor
>   id: CentralCommandOfficial
>   color: blue
>   bold: true # Доп параметры опционально
> ```
> 
> После в коде просто получаем id профессии и через `_protoManager.Index<CustomJobColor>(jobId)` (что так же твой любимый O(1)) получаем всю необходимую информацию о форматировании профессии.
> 
> Тогда никакого ручного кеширования делать будет не надо, никакой зависимости от локализации тоже не будет, и можно будет легко вводить новые параметры.
> 
> Есть ещё вариант в модификации существующего кода профессий и внесения туда дополнительных полей. Но боюсь миртону не понравится мерджить такое с апстримом

### Креатив, стоит относиться к ревью более обдуманно и внимательнее!
 Ладно одно дело ты не понял для чего нужен хэш словарь, который отвечает за мемоизацию уже вычисленных результатов, со всеми бывает, к критической ошибке это не приведёт
 
 ### Но делать значение jobPlayer не string? - когда у тебя буквально она в некоторых случаях будет иметь значение null - это то, что ни в коем случае делать нельзя.
 
 Теперь даже если в ревью ты будешь людям предлагать изменения, они будут просто "на всякий случай" не вводить такие изменения, так как в каком-то ревью ты предлагал такое изменение, которое бы приводило к критическим ошибкам. Так делать не стоит. **К ревью стоит относится внимательно и аккуратно!**

2024-11-29 10:31 UTC, Requiem4soul commented
### Изменения от Креатива, в связи с просьбой созданием критических ошибок и удалением оптимизации было целиком отклонено.
Ни одна критическая ошибка в коде не была принята, оптимизация так же сохранена. **Код не изменился**

2024-11-29 10:38 UTC, CREAsTIVE commented
> ### Изменения от Креатива, в связи с просьбой созданием критических ошибок и удалением оптимизации было целиком отклонено.
> Ни одна критическая ошибка в коде не была принята, оптимизация так же сохранена. **Код не изменился**

Ты не понял ни единого моего изменения. Зайди в ДС по возможности я объясню

2024-11-29 11:05 UTC, Requiem4soul commented
> > ### Изменения от Креатива, в связи с просьбой созданием критических ошибок и удалением оптимизации было целиком отклонено.
> > Ни одна критическая ошибка в коде не была принята, оптимизация так же сохранена. **Код не изменился**
> 
> Ты не понял ни единого моего изменения. Зайди в ДС по возможности я объясню

Креатив, за этот код **я отвечаю головой.** Я не могу осознанно вводить то, **что приведёт к фатальной ошибке**
![изображение](https://github.com/user-attachments/assets/0a041ad4-ed8d-4f33-aa6f-621bdb56e6df)


Попробуй просто сам сделать то, что ты предложил. Затем попробуй снять pda и не иметь в руках карту, и что-то сказать в рацию. При определении работы метод вернёт `null`, **который у тебя не обрабатывается**.

### Я не могу принять критическую ошибку ни при каких условиях. Креатив, пойми, это не потому что ты какой-то такой не хороший. А потому что я не имею право осознанно ввести критическую ошибку в свой код, который могут принять и использовать

2024-11-29 11:21 UTC, CREAsTIVE commented
@Requiem4soul Просто свяжись со мною через ДС, и я объясню. Данное изменение предполагает другие запрошенные изменения. Я готов при тебе все их применить и показать, что и как.

2024-11-30 09:40 UTC, Requiem4soul commented
@mirton14  Доброго Вам дня! Прошу прощения за пинг, но дело **реально важное**. 
В моём ПР(е) (Отображение должностей в рации. Обновлено под апстрим #49) товарищ Креатив в ревью предложил сделать код, который будет выдавать критическую ошибку вначале, затем фатальную, так как он исключил обработку null значений. Мною было это несколько раз указано Креативу (рассказывал почему приведёт, как проверить ошибку, делал скриншоты с указанием и видео с демонстрацией). Но до сих пор Креатив отказывается как-либо комментировать зачем он предложил мне в ревью критическую ошибку

Я бы ни слова не сказал, **не будь у товарища Креатива роль разработчика на данном сервере, что указывает на то, что он часть официальной команды разработчиков**. Хорошо я понимал хорошо свой код и сразу понял что такое допустить нельзя, но, если бы данное произошло с новичком, и такому новичку Креатив сказал сделать код, у которого будет критическая ошибка, которая крашнет сервера - **новичок мог бы необдуманно доверится официальному разработчику ИС, а потом нести ответственность за то, в чём он не виноват**.
Так же **это в целом убивает доверие к ревью, когда ты знаешь что другой разработчик может намеренно в ревью дать тебе код с критической ошибкой**. К здоровой атмосфере внутри разработчиков такое не приведёт

### Прошу вас разобраться в данной ситуации, так же выяснить у Креатива было это сделано намеренно или нет

2024-11-30 10:15 UTC, Qsan163 commented
потому что понабирают всяких девелоперов

2024-11-30 13:23 UTC, Requiem4soul commented
> потому что понабирают всяких девелоперов

А у вас есть хотя бы какой-то собес на джуна? Или джунов по сути почти всем выдают, но прав у них нет?

Просто это же реально опасно, если набегаторы эволюционируют, станут всем как "разработчик ИСа" предлагать ввести фатальные ошибки, а потом их коллеги набегаторы буду крашить сервера при помощи такого способа. Реально опасная же вещь

2024-11-30 13:46 UTC, CREAsTIVE commented
> > потому что понабирают всяких девелоперов
> 
> А у вас есть хотя бы какой-то собес на джуна? Или джунов по сути почти всем выдают, но прав у них нет?
> 
> Просто это же реально опасно, если набегаторы эволюционируют, станут всем как "разработчик ИСа" предлагать ввести фатальные ошибки, а потом их коллеги набегаторы буду крашить сервера при помощи такого способа. Реально опасная же вещь

Вы настоятельно продолжаете игнорировать мой ПР в вашу репу, где **рабочий** код, который вы конечно же не готовы проверять

2024-12-01 11:29 UTC, Qsan163 commented
> > потому что понабирают всяких девелоперов
> 
> А у вас есть хотя бы какой-то собес на джуна? Или джунов по сути почти всем выдают, но прав у них нет?
> 
> Просто это же реально опасно, если набегаторы эволюционируют, станут всем как "разработчик ИСа" предлагать ввести фатальные ошибки, а потом их коллеги набегаторы буду крашить сервера при помощи такого способа. Реально опасная же вещь

если я не ошибаюсь , то есть , изначально человек заполняет анкету , потом собес с HR - ом , устный или на крайняк онлайновый , а потом уже человек становится сотрудником

2024-12-01 12:21 UTC, Qsan163 commented
я слышал у нас нехватка кадров в девелоперной , возможно по этому такие есть

2024-12-28 22:33 UTC, mirton14 commented
Не считаю необходимым иметь конкретно эту фичу в билде.

2024-12-28 22:33 UTC, closed without merging