A, okay.
imperial-space/SS14-public pull request #91
Opened 2024-12-30 12:05 UTC by Seven2280

## About the PR
РЕСПРАЙТИРУЕТ ОТДЕЛ ГЕЙМЕРСКИХ ИНЖЕНЕРОВ 

## Why / Balance
СПРАЙТЫ ИНЖЕНЕРОВ НЕВЕРОЯТНО СИЛЬНО УСТАРЕЛИ НА ФОНЕ НОВЫХ СПРАЙТОВ. СПРАЙТЫ СКАФАНДРОВ ИНЖЕНЕРОВ НЕ ОБНОВЛЯЛИСЬ БОЛЕЕ 15 ЛЕТ.

## Technical details
Пришлось поменять некоторые лодауты, внести изменения в прототипы визардов (комментариями помечены) также были добавлены береты для СИ, ВИ, инжа. 

## Media
![gaymer](https://github.com/user-attachments/assets/f2aab47a-00a3-4b59-bef0-3c0eb64da916)

2024-12-30 12:13 UTC, SentryPrimies commented
Сайды шлема выглядят странно, а палитра атмоса немного блеклая, было бы неплохо тебе еще и магбуты респрайтнуть

2024-12-30 12:16 UTC, SentryPrimies commented
![изображение](https://github.com/user-attachments/assets/c28c074a-3296-4a0d-bb29-3b1d55b929bf)
Имхо моя изначальная версия спрайта лучше выглядела, у тебя словно шлем от более тяжелого скафандра присобачили, как-то не сочитаются.

2024-12-30 12:18 UTC, SentryPrimies commented on Resources/Textures/Clothing/Hands/Gloves/Color/yellow.rsi/equipped-HAND.png
здесь бы не помешал кубик, понапрасну шейдинг загрязнил

2024-12-30 12:18 UTC, SentryPrimies commented on Resources/Textures/Clothing/Hands/Gloves/Color/yellow.rsi/equipped-HAND-vox.png
а где измененный спрайт безпалых изолированных перчаток?

2024-12-30 12:19 UTC, SentryPrimies commented on Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/icon.png
Шлем вообще по-другому выглядит

2024-12-30 12:20 UTC, SentryPrimies commented on Resources/Textures/Clothing/Head/Hats/beret_ce.rsi/equipped-HELMET.png
Зачем в билде 2 белых берета с одинаковой палитрой?

2024-12-30 12:22 UTC, SentryPrimies commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/ce_turtle.rsi/equipped-INNERCLOTHING.png
юбку можно было и получше сделать, лучше перенеси её с респрайта рнд

2024-12-30 13:09 UTC, Mcdonaldsobamaburger commented on Resources/Textures/Clothing/Hands/Gloves/Color/yellow.rsi/equipped-HAND-vox.png
забыл, потом мб

2024-12-30 13:10 UTC, Mcdonaldsobamaburger commented on Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/icon.png
тебе кажется

2024-12-30 13:11 UTC, Mcdonaldsobamaburger commented
> ![изображение](https://private-user-images.githubusercontent.com/126711441/399289018-c28c074a-3296-4a0d-bb29-3b1d55b929bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjQ0NTcsIm5iZiI6MTczNTU2NDE1NywicGF0aCI6Ii8xMjY3MTE0NDEvMzk5Mjg5MDE4LWMyOGMwNzRhLTMyOTYtNGEwZC1iYjI5LTNiMWQ1NWI5MjliZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxMzA5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWIzODAwYjczMjk4YWE0MzliNzQxMjBjM2MwZmU0ZTU3NjMyYmEzZGYxOGJhNDU4YTVkNTUzYzE1N2RjNmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aLt7rAuCUC-_7sGH_xqqxDRAK5DXG0H8XM45cVM2Cy8) Имхо моя изначальная версия спрайта лучше выглядела, у тебя словно шлем от более тяжелого скафандра присобачили, как-то не сочитаются.

потому что у скафа замедло 40

2024-12-30 13:15 UTC, Seven2280 commented on Resources/Textures/Clothing/Head/Hats/beret_ce.rsi/equipped-HELMET.png
ты где второй увидел то

2024-12-30 13:16 UTC, SentryPrimies commented
> > ![изображение](https://private-user-images.githubusercontent.com/126711441/399289018-c28c074a-3296-4a0d-bb29-3b1d55b929bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjQ0NTcsIm5iZiI6MTczNTU2NDE1NywicGF0aCI6Ii8xMjY3MTE0NDEvMzk5Mjg5MDE4LWMyOGMwNzRhLTMyOTYtNGEwZC1iYjI5LTNiMWQ1NWI5MjliZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxMzA5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWIzODAwYjczMjk4YWE0MzliNzQxMjBjM2MwZmU0ZTU3NjMyYmEzZGYxOGJhNDU4YTVkNTUzYzE1N2RjNmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aLt7rAuCUC-_7sGH_xqqxDRAK5DXG0H8XM45cVM2Cy8) Имхо моя изначальная версия спрайта лучше выглядела, у тебя словно шлем от более тяжелого скафандра присобачили, как-то не сочитаются.
> 
> потому что у скафа замедло 40

🖕

2024-12-30 13:29 UTC, SentryPrimies commented on Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/icon.png
> тебе кажется

нет, он должен как-то так выглядеть по идеи, верх оранжевый низ черный
![изображение](https://github.com/user-attachments/assets/e680e40a-81a6-43e3-bd66-a4498b97d083)

2024-12-30 13:30 UTC, SentryPrimies commented on Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/icon.png
> тебе кажется

![изображение](https://github.com/user-attachments/assets/687654a9-9f8e-47e1-ae14-0934153ff93a)
хищник с квадратной челюстью против девственника

2024-12-30 13:31 UTC, SentryPrimies commented on Resources/Textures/Clothing/Head/Hats/beret_ce.rsi/equipped-HELMET.png
> ты где второй увидел то

капитанский. Это просто белый берет без отличительных черт

2025-01-06 16:05 UTC, NeronClaudius requested changes
Квадраты убрать. Откуда спрайты?
![image](https://github.com/user-attachments/assets/fb654ccc-493e-483d-a46c-f026dd9e154b)

2025-01-06 16:10 UTC, Mcdonaldsobamaburger commented
> Квадраты убрать. Откуда спрайты? ![image](https://private-user-images.githubusercontent.com/130681113/400478310-fb654ccc-493e-483d-a46c-f026dd9e154b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxODAwMDUsIm5iZiI6MTczNjE3OTcwNSwicGF0aCI6Ii8xMzA2ODExMTMvNDAwNDc4MzEwLWZiNjU0Y2NjLTQ5M2UtNDgzZC1hNDZjLWYwMjZkZDllMTU0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxNjA4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzkxMzI3MWZkYTQwODIyOGExMGVlOGQzNDUxZDEyY2UxYWE1M2U2YTU1NTgwMTI5OWU3N2JmMmM4ZTNkYmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dk-4bHUlnZMQtDdgscS3RvlBzLUGLBx5OGtYq2yq1Dk)

1. Без квадратов спрайт максимально убогий. Это в любом случае лучше чем то, что в билде. Комьюнити дискорда оценило спрайт на 50 лайков и 2 диза.
2. Сделаны с нуля

2025-01-06 16:24 UTC, Mcdonaldsobamaburger commented
Если наличие кубиков на спрайте хардов это причина для отказа от респрайта самого стилистически устаревшего отдела, то закрывайте пр. Убирать кубики я не собираюсь

2025-01-06 17:21 UTC, SentryPrimies commented
>  Откуда спрайты? ![image](https://private-user-images.githubusercontent.com/130681113/400478310-fb654ccc-493e-483d-a46c-f026dd9e154b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxODM3NDcsIm5iZiI6MTczNjE4MzQ0NywicGF0aCI6Ii8xMzA2ODExMTMvNDAwNDc4MzEwLWZiNjU0Y2NjLTQ5M2UtNDgzZC1hNDZjLWYwMjZkZDllMTU0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxNzEwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjhhMzQxMjE4NGQ5ZmNiNjM5YjlkY2E1YjlmN2ViYmYwZGIwZmNiODllMjQ5NmU4MmY1YWFhOGRmZjcyMzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U8BRNkTGCdvf3PElCQHp6bov9a1eOlLh_ZQRjAbB4yI)

Ты не поверишь
![изображение](https://github.com/user-attachments/assets/0849a988-e5cb-44cd-a635-e2f94e565d29)
![изображение](https://github.com/user-attachments/assets/8588d796-48bd-46bf-b8d9-83b29ee7f726)
![изображение](https://github.com/user-attachments/assets/4e96939f-189a-4b9a-a8b8-1ab07197802f)
![изображение](https://github.com/user-attachments/assets/23a12def-149f-4d6b-aebb-f7fdccdf63c0)
![изображение](https://github.com/user-attachments/assets/821c0a26-9276-4036-9981-f9d44de739b9)
![изображение](https://github.com/user-attachments/assets/7a7282b0-8697-46d3-bacd-7b525207eb74)
![изображение](https://github.com/user-attachments/assets/42c3ea10-e747-4e9d-82b7-0c640dd0cdaa)
![изображение](https://github.com/user-attachments/assets/66c56a1c-0844-4b7c-8312-2c436dc66419)
![изображение](https://github.com/user-attachments/assets/87c3b2b6-7145-4bda-bef4-9897773b585f)

2025-01-06 17:25 UTC, closed without merging

2025-01-10 11:26 UTC, Bl1tz542 commented
Я искренне не понимаю претензии к кубикам. Кубики были использованы были и ранее в билде, причем многократно. Сейчас же придумали любой спрайт где о боже упаси есть "кубики" лего отклоняют, вот тебе и стагнация спрайтов и стилистики билда, как такового.

2025-01-10 11:30 UTC, Bl1tz542 commented
Была бы критика конструктивной и более объективной, то может бы предъяву и понял, единственное, что я смог за все эти пры отклоненные увидеть, так это "КУБИКИ", больше никакой конструктивности в доводах.

2025-01-10 11:32 UTC, Mcdonaldsobamaburger commented
> Я искренне не понимаю претензии к кубикам. Кубики были использованы были и ранее в билде, причем многократно. Сейчас же придумали любой спрайт где о боже упаси есть "кубики" лего отклоняют, вот тебе и стагнация спрайтов и стилистики билда, как такового.

Я уже говорил об этом, всем похуй. Кубики - харам

2025-01-10 11:35 UTC, Bl1tz542 commented
> > Я искренне не понимаю претензии к кубикам. Кубики были использованы были и ранее в билде, причем многократно. Сейчас же придумали любой спрайт где о боже упаси есть "кубики" лего отклоняют, вот тебе и стагнация спрайтов и стилистики билда, как такового.
> 
> Я уже говорил об этом, всем похуй. Кубики - харам

Да я понял, тут конструктивности нет. Есть только "скобачки)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))"

2025-01-10 23:07 UTC, ArturUr1 commented
Уважаемый "маэстро спрайтов" на Блитзе (и я знаю, что ты не Обама, который это и рисовал). Есть требования, которые предъявляют для добавления в билд. И всего два исхода. **Первое** - упереться и не выполнять. Резонно разработка/спрайт будет отклонен. И не надо потом возмущаться из-за этого исхода. Шо, Neron виновата, что уперлись с кубизмом своим?)
**Второе** - согласиться, что требованиям не соответствует и поменять под них.

В вашем случае первое. Каждый раз. Как под копирку у каждого. Не нужны билду ваши кубики. И то, что вы подсмотрели это у какого-то художника и теперь лоббируете это - ваще мало кого интересует и не наша забота. Лезть в это ваще не хотел и максимально игнорировал, но раз так - окей. Не выполняете - будет отклоняться. 
И да, защитой компашки своей и их спрайтов в другом месте занимайся))))))))))))))))))))))))))))

2025-01-11 00:09 UTC, Mcdonaldsobamaburger commented
> Уважаемый "маэстро спрайтов" на Блитзе (и я знаю, что ты не Обама, который это и рисовал). Есть требования, которые предъявляют для добавления в билд. И всего два исхода. **Первое** - упереться и не выполнять. Резонно разработка/спрайт будет отклонен. И не надо потом возмущаться из-за этого исхода. Шо, Neron виновата, что уперлись с кубизмом своим?) **Второе** - согласиться, что требованиям не соответствует и поменять под них.
> 
> В вашем случае первое. Каждый раз. Как под копирку у каждого. Не нужны билду ваши кубики. И то, что вы подсмотрели это у какого-то художника и теперь лоббируете это - ваще мало кого интересует и не наша забота. Лезть в это ваще не хотел и максимально игнорировал, но раз так - окей. Не выполняете - будет отклоняться. И да, защитой компашки своей и их спрайтов в другом месте занимайся))))))))))))))))))))))))))))

Идеи не принадлежат одному конкретному человеку или народу -- они принадлежат всем нам; То, что мы подсмотрели какие-то техники у одного художника -- естественный ход вещей. Леонардо да винчи подсмотрел некоторые идеи у витрувия, джотто и мазаччо, филлипо брунеллески... А Да винчи уже вдохновились Микеланджело, рафаэль санти и остальные художники модерна и постмодерна. Ничего зазорного в этом нет. И кубиками пользуется не один-единственный спрайтер, у которого "мы подлизали идею". Таких 20 человек можно насчитать, а то и больше. Так и развивается живопись -- на костях прошлого человек воздвигает что-то своё. Оно непременно осыпется и станет фундаментом для следующих поколений. Именно из за этого отрицалова ваш билд и выглядит так отстало в сравнении с остальными.Не нужны билду? Игроки считают иначе. Или в игру ничего нового кроме перекраса имеющихся спрайтов для гмов ничего не надо? Стилистика? Ну, допустим, 2018 Новотг. Тайлы? Тау сети, еще с корвуха. Стены? Тау сети, еще с корвуха. Спрайты одежды? Тг. Дженерик набор русского билда. По скринам не поймёшь Корвух это иль ваш билд. Только вот уже как 2 года русские билды отходят от этого, а вы всё еще там, в 2022 году. И те спрайты, что вы добавляете, без обид, не дотягивают и до новотг. Просто старотг со всеми его огрехами -- Бандинг, Шмандинг, Миксели, ужасная палитра, невыразительность, и прочая, прочая, прочая. А одним из основных двигателей "сс14" является её "относительная красота" по отношению к сс13.

2025-01-11 08:29 UTC, Bl1tz542 commented
> Уважаемый "маэстро спрайтов" на Блитзе (и я знаю, что ты не Обама, который это и рисовал). Есть требования, которые предъявляют для добавления в билд. И всего два исхода. **Первое** - упереться и не выполнять. Резонно разработка/спрайт будет отклонен. И не надо потом возмущаться из-за этого исхода. Шо, Neron виновата, что уперлись с кубизмом своим?) **Второе** - согласиться, что требованиям не соответствует и поменять под них.
> 
> В вашем случае первое. Каждый раз. Как под копирку у каждого. Не нужны билду ваши кубики. И то, что вы подсмотрели это у какого-то художника и теперь лоббируете это - ваще мало кого интересует и не наша забота. Лезть в это ваще не хотел и максимально игнорировал, но раз так - окей. Не выполняете - будет отклоняться. И да, защитой компашки своей и их спрайтов в другом месте занимайся))))))))))))))))))))))))))))

Во первых, я не позиционирую себя в качесетве маэстро спрайтов, я лишь обычный потребитель способный проводить критический анализ на базовом уровне. Копирка, где ранее было об этом указанно? Индвидуум вышел привел доказательство того-что данные "спрайты" были произведены самими авторами ранее. Вы же в свою очередь данный факт игнорируете, к моему огромному сожалению. "Не нужны билду кубики ваши", при этом автор указал, что "кубики" были исполльзованы многократно в билде, при этом данный факт упорно игнорируется. Лоббированием, а именно давлением на Вас, как на личность никто не занимался. Вас так обидел тейк со смайликами, что вы решили его использовать повсеместно? Я не понимаю о какой метакомпашке речь,, если мне понравился спрайт и я хочу видеть его в игре, то яразве не могу поделиться своим мнением на том или ином ресурсе? Мое мнение разве является чем-то важным, что о Боже меня приплетают к принадлежности к "метакомпашкам". Я продолжаю не видеть ответы на вопросы ранее мной сказанной и здесь повторенным. Вы отвечаете только на то, что вам удобно, а это вид манипуляций. Я не ожидал подобного на самом деле, это с какой-то стороны меня даже расстраивает. У вас люди, условное состоящие в "метакомпашках"  это Дельты, как по Олдосу Хаксли? Мне кажется, что столь примитивное классовое суждение не является хорошим примером для меня, как индвидуума в частности. Я не получил ответы, опять же. Я после вами сказанного даже не надеюсь. Я расстроен, я ожидал от Вас большего, чем простой троллинг приправленный долей ненависти.